import type { Event, InterestCheck, Squad, Friend } from "./ui-types";

export const DEMO_EVENTS: Event[] = [
  {
    id: "demo-event-1",
    title: "Dusk to Dawn: Anadelia b2b VTSS",
    venue: "Bossa Nova Civic Club",
    date: "Fri, Feb 14",
    time: "11PM–5AM",
    vibe: ["techno", "late night"],
    image: "https://images.unsplash.com/photo-1598387993441-a364f854c3e1?w=600&q=80",
    igHandle: "@baborecords",
    saved: false,
    isDown: false,
    peopleDown: [
      { name: "Sara", avatar: "S", mutual: true },
      { name: "Nickon", avatar: "N", mutual: true },
      { name: "devon.mp3", avatar: "D", mutual: false },
      { name: "raya_k", avatar: "R", mutual: false },
      { name: "jun.wav", avatar: "J", mutual: false },
    ],
  },
  {
    id: "demo-event-2",
    title: "Mood Ring Presents: Ambient Wednesdays",
    venue: "Mood Ring",
    date: "Wed, Feb 19",
    time: "8PM–12AM",
    vibe: ["ambient", "chill"],
    image: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&q=80",
    igHandle: "@moodringbk",
    saved: true,
    isDown: true,
    peopleDown: [
      { name: "Janelle", avatar: "J", mutual: true },
      { name: "ambient.boy", avatar: "A", mutual: false },
    ],
  },
  {
    id: "demo-event-3",
    title: "MUTUAL AID RAVE — all door $ donated",
    venue: "Elsewhere Zone One",
    date: "Sat, Feb 22",
    time: "10PM–4AM",
    vibe: ["house", "community"],
    image: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=600&q=80",
    igHandle: "@elsewherespace",
    saved: false,
    isDown: false,
    peopleDown: [
      { name: "Luke", avatar: "L", mutual: true },
      { name: "Sara", avatar: "S", mutual: true },
      { name: "mx.flora", avatar: "M", mutual: false },
      { name: "khai_dances", avatar: "K", mutual: false },
      { name: "tonnno", avatar: "T", mutual: false },
      { name: "reese.wav", avatar: "R", mutual: false },
      { name: "bklynboi", avatar: "B", mutual: false },
    ],
  },
  {
    id: "demo-event-4",
    title: "Film Photo Walk — Bushwick to Ridgewood",
    venue: "Meet @ Jefferson L stop",
    date: "Sun, Feb 23",
    time: "2PM–5PM",
    vibe: ["photography", "daytime"],
    image: "https://images.unsplash.com/photo-1495745966610-2a67f2297e5e?w=600&q=80",
    igHandle: "@filmnerds.bk",
    saved: false,
    isDown: false,
    peopleDown: [
      { name: "Nickon", avatar: "N", mutual: true },
      { name: "grain.queen", avatar: "G", mutual: false },
      { name: "portra400", avatar: "P", mutual: false },
    ],
  },
];

export const DEMO_CHECKS: InterestCheck[] = [
  {
    id: "demo-check-1",
    text: "dinner tonight? thinking thai or korean",
    author: "Sara",
    timeAgo: "5m",
    expiresIn: "23h",
    expiryPercent: 4,
    responses: [
      { name: "Nickon", avatar: "N", status: "down" },
      { name: "Janelle", avatar: "J", status: "down" },
    ],
  },
  {
    id: "demo-check-2",
    text: "anyone wanna do a museum day this weekend? maybe MoMA or the Whitney",
    author: "Luke",
    timeAgo: "12h",
    expiresIn: "12h",
    expiryPercent: 60,
    responses: [
      { name: "Sara", avatar: "S", status: "down" },
      { name: "devon.mp3", avatar: "D", status: "maybe" },
      { name: "raya_k", avatar: "R", status: "down" },
    ],
  },
  {
    id: "demo-check-5",
    text: "rooftop drinks saturday? bringing a speaker 🔊",
    author: "Devon",
    timeAgo: "3h",
    expiresIn: "21h",
    expiryPercent: 12,
    responses: [
      { name: "Sara", avatar: "S", status: "down" },
    ],
    viaFriendName: "Sara",
  },
  {
    id: "demo-check-3",
    text: "coffee run?",
    author: "Janelle",
    timeAgo: "22h",
    expiresIn: "2h",
    expiryPercent: 92,
    responses: [],
  },
  {
    id: "demo-check-4",
    text: "rooftop hangs friday? 🌆",
    author: "You",
    timeAgo: "2m",
    expiresIn: "24h",
    expiryPercent: 1,
    responses: [
      { name: "Sara", avatar: "S", status: "down" },
    ],
    isYours: true,
  },
];

export const DEMO_TONIGHT: Event[] = [
  {
    id: "demo-tonight-1",
    title: "Rooftop DJ Set — House & Disco",
    venue: "The Roof BK",
    neighborhood: "Williamsburg",
    date: "Tonight",
    time: "9PM–2AM",
    vibe: ["house", "disco"],
    image: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600&q=80",
    igHandle: "@theroofbk",
    saved: false,
    isDown: false,
    isPublic: true,
    peopleDown: [
      { name: "alex.wav", avatar: "A", mutual: false },
      { name: "dj_nova", avatar: "D", mutual: false },
      { name: "brooklynite", avatar: "B", mutual: false },
    ],
  },
  {
    id: "demo-tonight-2",
    title: "Open Mic Comedy Night",
    venue: "Union Hall",
    neighborhood: "Park Slope",
    date: "Tonight",
    time: "8PM–11PM",
    vibe: ["comedy", "chill"],
    image: "https://images.unsplash.com/photo-1585699324551-f6c309eedeca?w=600&q=80",
    igHandle: "@unionhallny",
    saved: false,
    isDown: false,
    isPublic: true,
    peopleDown: [
      { name: "laughs4days", avatar: "L", mutual: false },
      { name: "mic_drop", avatar: "M", mutual: false },
    ],
  },
  {
    id: "demo-tonight-3",
    title: "Gallery Opening — New Brooklyn Artists",
    venue: "PRACTICE",
    neighborhood: "Bushwick",
    date: "Tonight",
    time: "7PM–10PM",
    vibe: ["art", "free"],
    image: "https://images.unsplash.com/photo-1561214115-f2f134cc4912?w=600&q=80",
    igHandle: "@practice.bk",
    saved: false,
    isDown: false,
    isPublic: true,
    peopleDown: [
      { name: "artlover", avatar: "A", mutual: false },
      { name: "galleryhopper", avatar: "G", mutual: false },
      { name: "brush.strokes", avatar: "B", mutual: false },
      { name: "curator_x", avatar: "C", mutual: false },
    ],
  },
  {
    id: "demo-tonight-4",
    title: "Techno til Dawn — Basement Party",
    venue: "Undisclosed",
    neighborhood: "Ridgewood",
    date: "Tonight",
    time: "12AM–6AM",
    vibe: ["techno", "underground"],
    image: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=600&q=80",
    igHandle: "@rvmtcollective",
    saved: false,
    isDown: false,
    isPublic: true,
    peopleDown: [
      { name: "bass.head", avatar: "B", mutual: false },
      { name: "techno_kid", avatar: "T", mutual: false },
      { name: "4amcrew", avatar: "4", mutual: false },
      { name: "darkroom", avatar: "D", mutual: false },
      { name: "synth.witch", avatar: "S", mutual: false },
    ],
  },
];

export const DEMO_SQUADS: Squad[] = [
  {
    id: "demo-squad-1",
    name: "Bossa squad",
    event: "Dusk to Dawn: Anadelia b2b VTSS — Feb 14",
    members: [
      { name: "Sara", avatar: "S" },
      { name: "Nickon", avatar: "N" },
      { name: "You", avatar: "K" },
    ],
    messages: [
      { sender: "Sara", text: "ok we're actually doing this right", time: "2:34 PM" },
      { sender: "Nickon", text: "yup yup, what time we thinking?", time: "2:35 PM" },
      { sender: "You", text: "i can get there around 11:30?", time: "2:38 PM", isYou: true },
      { sender: "Sara", text: "perfect. pregame at mine first?", time: "2:40 PM" },
      { sender: "Nickon", text: "down", time: "2:41 PM" },
      { sender: "Sara", text: "who's pregaming?", time: "2:45 PM" },
    ],
    lastMsg: "Sara: who's pregaming?",
    time: "2m",
  },
  {
    id: "demo-squad-2",
    name: "Ambient Wednesday",
    event: "Mood Ring Presents: Ambient Wednesdays — Feb 19",
    members: [
      { name: "Janelle", avatar: "J" },
      { name: "You", avatar: "K" },
    ],
    messages: [
      { sender: "Janelle", text: "this is gonna be so chill", time: "Yesterday" },
      { sender: "You", text: "fr, i need it after this week", time: "Yesterday", isYou: true },
      { sender: "Janelle", text: "same 😮‍💨", time: "Yesterday" },
      { sender: "You", text: "down for dinner before?", time: "11:23 AM", isYou: true },
    ],
    lastMsg: "You: down for dinner before?",
    time: "1h",
  },
];

export const DEMO_FRIENDS: Friend[] = [
  { id: "demo-friend-1", name: "Sara", username: "sara.nyc", avatar: "S", status: "friend", availability: "open" },
  { id: "demo-friend-2", name: "Nickon", username: "nickon", avatar: "N", status: "friend", availability: "awkward" },
  { id: "demo-friend-3", name: "Janelle", username: "janelle.k", avatar: "J", status: "friend", availability: "not-available" },
  { id: "demo-friend-4", name: "Luke", username: "luke_bk", avatar: "L", status: "friend", availability: "open" },
];

export const DEMO_SUGGESTIONS: Friend[] = [
  { id: "demo-suggest-1", name: "Devon", username: "devon.mp3", avatar: "D", status: "none" },
  { id: "demo-suggest-2", name: "Raya", username: "raya_k", avatar: "R", status: "incoming" },
  { id: "demo-suggest-3", name: "Marcus", username: "marcus.wav", avatar: "M", status: "pending" },
  { id: "demo-suggest-4", name: "Zoe", username: "zoe.creates", avatar: "Z", status: "none" },
];

export const DEMO_NOTIFICATIONS: { id: string; type: string; title: string; body: string | null; related_user_id: string | null; related_squad_id: string | null; related_check_id: string | null; is_read: boolean; created_at: string }[] = [
  { id: "n1", type: "friend_request", title: "Raya wants to be friends", body: "@raya_k sent you a request", related_user_id: null, related_squad_id: null, related_check_id: null, is_read: false, created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString() },
  { id: "n2", type: "check_response", title: "Sara is down!", body: "Responded to your check \"rooftop hangs friday?\"", related_user_id: null, related_squad_id: null, related_check_id: null, is_read: false, created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString() },
  { id: "n3", type: "friend_accepted", title: "Devon accepted your request", body: "You and @devon.mp3 are now friends", related_user_id: null, related_squad_id: null, related_check_id: null, is_read: true, created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString() },
];

export const DEMO_SEARCH_USERS: Friend[] = [
  { id: "demo-search-1", name: "Alex Kim", username: "alex.k", avatar: "A", status: "none" },
  { id: "demo-search-2", name: "Mia Chen", username: "mia.creates", avatar: "M", status: "none" },
  { id: "demo-search-3", name: "Jordan Lee", username: "jordan.lee", avatar: "J", status: "none" },
  { id: "demo-search-4", name: "Kai Nakamura", username: "kai.nak", avatar: "K", status: "none" },
];
